conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
  win_64: github_actions
